# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Configuration file for MODIS R scripts (Version 7)  
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------
# Define Logging level
# ----------------------------------------------------------------------------------------

# Select the logging level. It must be one of these:
# ERROR 
# WARNING
# INFO

log.level  :  "INFO"

# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Sensor being analyzed ("Aqua" or "Terra")
# ----------------------------------------------------------------------------------------

sensor  :  "Aqua"		    # MODIS sensor to be analyzed
sensor_uc  :  "AQUA"	  # Name of sensor in upper case

# sensor  :  "Terra"  	# MODIS sensor to be analyzed
# sensor_uc  :  "TERRA"	# Name of sensor in upper case
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Version of matchups' calibration collection
# ----------------------------------------------------------------------------------------

collection  :  6
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Information about matchups
# ----------------------------------------------------------------------------------------

matchups  :
  format   :  "OLD"
  version  :  "6b"
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Information about geophysical variable being estimated, and algorithm details
# ----------------------------------------------------------------------------------------

geophys.var  :  "SST" 		 	# Geophysical variable estimated can be "SST" or "SST4"

algorithm  :
  type  :  "latband1" 						# SST algorithm type
  version.name  :  "6"		        # SST algorithm version
  coefficients.version  :  "6.3"	# Version for algorithm coefficients
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Directory where input matchups are located
# ----------------------------------------------------------------------------------------

matchups.indir  :  "D:/Matchup_files/MODIS/"
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Base directory for results 
# ----------------------------------------------------------------------------------------

results.dir   :  "D:/Matchups/MODIS/results/" 		# Directory for results
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Directory where ancillary geographic information is located 
# ----------------------------------------------------------------------------------------

geo.dir  :  "D:/ENSO-Data/Other Data/Natural Earth/"  # Used to fetch ocean basin names
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Define if ALL matchups will be kept or a sample will be taken
# ----------------------------------------------------------------------------------------

match.sample  :  TRUE
match.prop  :  0.4      # Proportion of matchups that will be kept
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Define if ALL variables in input matchup records will be kept, or a subset is extracted
# ----------------------------------------------------------------------------------------

keep.all.vars  :  FALSE 		# If TRUE, keep all variables in input file
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Define if data from ships are kept or not. In V6b ship data are excluded...

keep.ships  :  FALSE        # If TRUE, keep matchups form ships, else skip them...
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# Define boundary between regimes of BT difference for channels in 11um range
# ----------------------------------------------------------------------------------------

MODIS.BTdiff.threshold  :  0.7	# In deg C
# ----------------------------------------------------------------------------------------



# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------